spring.application.name=acessosaude

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cnes_db
spring.datasource.username=postgres
spring.datasource.password=sua_senha

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true